name: FBA
favicon: null
layout_spectrum: 0.553935207426548
typography_spectrum: 0.13671498652547598
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1373481152113527
  lightness: 0.7316238512285054
  saturation: 0.8055547911208123
  rhythmicContrast: 0.8728127412032336
purpose: []
